services:
  #nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
      target: app
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: ./php/Dockerfile
  db:
    image: mysql:8.4.5
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php

volumes:
  mysqldata:
    